# Generated by Django 4.1.4 on 2023-05-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
